modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="zetamod"
version="1.0.0"
displayName="ZetaMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="micha, MCreator"

[[dependencies.zetamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




